version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - memcached
      - rabbitmq

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: admin123
    ports:
      - "3306:3306"

  memcached:
    image: memcached
    ports:
      - "11211:11211"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"